from enum import Enum


class AssertionsAssertType(str, Enum):
    BGP_PEER_ESTABLISHED = "BGP_PEER_ESTABLISHED"
    CONFIG_ADDED_TO_DB = "CONFIG_ADDED_TO_DB"
    DEVICE_CONNECTED_TO_CLOUD = "DEVICE_CONNECTED_TO_CLOUD"
    DEVICE_CONNECTED_TO_FABRIC = "DEVICE_CONNECTED_TO_FABRIC"
    DEVICE_RESOURCE_USAGE_BELOW_THRESHOLD = "DEVICE_RESOURCE_USAGE_BELOW_THRESHOLD"
    MANAGEMENT_PORT_CONFIG_SAME = "MANAGEMENT_PORT_CONFIG_SAME"
    PORT_CONNECTION_SPEED_MATCH = "PORT_CONNECTION_SPEED_MATCH"
    PORT_EXPECTED_NEIGHBOR = "PORT_EXPECTED_NEIGHBOR"
    PORT_LINK_DOWN = "PORT_LINK_DOWN"
    PORT_LINK_UP = "PORT_LINK_UP"
    PORT_NOT_CONNECTED_TO_FABRIC = "PORT_NOT_CONNECTED_TO_FABRIC"
    PORT_SPEED_CONSISTENT = "PORT_SPEED_CONSISTENT"
    STATIC_DEFAULT_ROUTE_EXISTS = "STATIC_DEFAULT_ROUTE_EXISTS"
    VLAN_HAS_TRAFFIC = "VLAN_HAS_TRAFFIC"

    def __str__(self) -> str:
        return str(self.value)
