from enum import Enum


class ModelsObjectType(str, Enum):
    API_KEY = "API_KEY"
    BEARER_TOKEN = "BEARER_TOKEN"
    BGP_PEER = "BGP_PEER"
    BGP_POLICY = "BGP_POLICY"
    CERTIFICATES = "CERTIFICATES"
    DEVICE = "DEVICE"
    DHCP_RELAY = "DHCP_RELAY"
    FABRIC = "FABRIC"
    FABRIC_TRANSACTION = "FABRIC_TRANSACTION"
    LOOPBACK = "LOOPBACK"
    MANAGEMENT_PORT = "MANAGEMENT_PORT"
    NETWORK_PORT = "NETWORK_PORT"
    NODE = "NODE"
    NOTIFICATION_ENDPOINT = "NOTIFICATION_ENDPOINT"
    ORGANIZATION = "ORGANIZATION"
    PER_VLAN_STP = "PER_VLAN_STP"
    PORT_BREAKOUT = "PORT_BREAKOUT"
    PORT_CHANNEL = "PORT_CHANNEL"
    PORT_CONNECTION = "PORT_CONNECTION"
    PREFIX_LIST = "PREFIX_LIST"
    REST_KEY = "REST_KEY"
    STATIC_ROUTES = "STATIC_ROUTES"
    SUB_INTERFACE = "SUB_INTERFACE"
    SVI = "SVI"
    TENANT = "TENANT"
    USER = "USER"
    VLAN = "VLAN"
    VNI = "VNI"
    VRF = "VRF"

    def __str__(self) -> str:
        return str(self.value)
