from enum import Enum


class ModelsAssertCategoryType(str, Enum):
    ASSERT_CATEGORY_COMPLIANCE = "ASSERT_CATEGORY_COMPLIANCE"
    ASSERT_CATEGORY_FABRIC = "ASSERT_CATEGORY_FABRIC"
    ASSERT_CATEGORY_HOST_ATTACHMENT = "ASSERT_CATEGORY_HOST_ATTACHMENT"
    ASSERT_CATEGORY_SECURITY = "ASSERT_CATEGORY_SECURITY"
    ASSERT_CATEGORY_SERVICES = "ASSERT_CATEGORY_SERVICES"
    ASSERT_CATEGORY_UPSTREAM_PEERING = "ASSERT_CATEGORY_UPSTREAM_PEERING"

    def __str__(self) -> str:
        return str(self.value)
